services:
  auth-python:
    build: ./services/auth-python
    expose:
      - "8000"

  billing-csharp:
    build: ./services/billing-csharp
    # this is an "internal service", so we don't need to expose it to the outside world
    # ports:
    #   - "8003:80"
    environment:
      - BILLING_SECRET=topsecretvalue
    expose:
      - "80"


  orders-java:
    build: ./services/orders-java
    expose:
      - "8002"
    links:
      - auth-python
      - billing-csharp
    environment:
      - BILLING_SECRET=topsecretvalue
      - AUTH_SERVICE_URL=http://auth-python:8000
      - BILLING_SERVICE_URL=http://billing-csharp

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - AUTH_URL=http://auth-python:8000
      - ORDERS_URL=http://orders-java:8080
    links:
      - auth-python
      - orders-java