name: Jira CFR/MTTR via Actions
on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Jira login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://linearb-team-dt3f5efh.atlassian.net/
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - id: reviews
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = context.payload.pull_request.number;
            const reviews = await github.paginate(
              github.rest.pulls.listReviews,
              { owner, repo, pull_number: pr, per_page: 100 }
            );
            // Count all APPROVED reviews (includes bots)
            core.setOutput('approvals', String(reviews.filter(r => r.state === 'APPROVED').length));

      # Open bug if merged with 0 reviews
      - name: Create bug (no reviews)
        id: create_bug
        if: >
          !contains(format('{0}', github.event.pull_request.title || ''), 'rollback') &&
          steps.reviews.outputs.approvals == '0' 
        uses: atlassian/gajira-create@v3
        with:
          project: SCRUM
          issuetype: Bug
          summary: "[DEMO] Bug after PR #${{ github.event.pull_request.number }}"
          description: "Merged without review: ${{ github.event.pull_request.html_url }}"
          fields: '{"labels": ["demo","autogenerated"], "priority":{"name":"Highest"}}'

      - name: Revert last commit on main (prepare changes)
        if: >
          !contains(format('{0}', github.event.pull_request.title || ''), 'rollback') &&
          steps.reviews.outputs.approvals == '0' &&
          steps.create_bug.outputs.issue != ''
        run: |
          set -euo pipefail
          # Ensure we are on main (checkout already uses ref: main)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Revert the latest commit on main (squash commits are single-parent, so no -m 1)
          git revert --no-edit HEAD

      - name: Create rollback PR
        if: >
          !contains(format('{0}', github.event.pull_request.title || ''), 'rollback') &&
          steps.reviews.outputs.approvals == '0' &&
          steps.create_bug.outputs.issue != ''
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auth-config-rollback-${{ github.run_id }}
          base: main
          title: "${{ steps.create_bug.outputs.issue }} rollback: restore bob test user"
          commit-message: "Revert ${{ github.sha }}"
          body: |
            Rollback referencing ${{ steps.create_bug.outputs.issue }} for PR #${{ github.event.pull_request.number }}.
          delete-branch: true

      - name: Merge rollback PR
        if: >
          !contains(format('{0}', github.event.pull_request.title || ''), 'rollback') &&
          steps.reviews.outputs.approvals == '0' &&
          steps.create_bug.outputs.issue != '' &&
          steps.create_pr.outputs.pull-request-number != ''
        uses: peter-evans/merge-pull-request@v3
        with:
          pull-request: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: merge
          delete-branch: true

      - name: Search for open demo Bug
        if: ${{ contains(github.event.pull_request.title, 'rollback') }}
        id: find
        uses: tomhjp/gh-action-jira-search@v0.2.2
        with:
          jql: >
            project = SCRUM AND labels in (demo, autogenerated)
            AND statusCategory != Done ORDER BY created DESC

      - name: Transition Bug to Done
        if: ${{ contains(github.event.pull_request.title, 'rollback') && steps.find.outputs.issue != '' }}
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: Done
