name: Jira CFR/MTTR via Actions
on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read

jobs:
  jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Jira login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://linearb-team-dt3f5efh.atlassian.net/
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - id: reviews
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = context.payload.pull_request.number;
            const reviews = await github.paginate(
              github.rest.pulls.listReviews,
              { owner, repo, pull_number: pr, per_page: 100 }
            );
            // Count all APPROVED reviews (includes bots)
            core.setOutput('approvals', String(reviews.filter(r => r.state === 'APPROVED').length));

      # Open bug if merged with 0 reviews
      - name: Create bug (no reviews)
        if: >
          !contains(format('{0}', github.event.pull_request.title || ''), 'rollback') &&
          steps.reviews.outputs.approvals == '0' 
        uses: atlassian/gajira-create@v3
        with:
          project: SCRUM
          issuetype: Bug
          summary: "[DEMO] Bug after PR #${{ github.event.pull_request.number }}"
          description: "Merged without review: ${{ github.event.pull_request.html_url }}"
          fields: '{"labels": ["demo","autogenerated"], "priority":{"name":"Highest"}}'

      - name: Search for open demo Bug
        if: ${{ contains(github.event.pull_request.title, 'rollback') }}
        id: find
        uses: tomhjp/gh-action-jira-search@v0.2.2
        with:
          jql: >
            project = SCRUM AND labels in (demo, autogenerated)
            AND statusCategory != Done ORDER BY created DESC

      - name: Transition Bug to Done
        if: ${{ contains(github.event.pull_request.title, 'rollback') && steps.find.outputs.issue != '' }}
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: Done
